# Generated by Django 6.0.4 on 2026-07-21 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('politics', 'Politics'), ('business', 'Business'), ('sports', 'Sports'), ('technology', 'Technology'), ('world', 'World'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('finance', 'Finance'), ('science', 'Science')], default='general', max_length=20)),
                ('bias', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('bias_score', models.IntegerField(default=50)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('left_sources', models.PositiveIntegerField(default=0)),
                ('center_sources', models.PositiveIntegerField(default=0)),
                ('right_sources', models.PositiveIntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('rss_url', models.URLField(unique=True)),
                ('logo', models.URLField(blank=True)),
                ('country', models.CharField(choices=[('pk', 'Pakistan'), ('us', 'United States'), ('gb', 'United Kingdom'), ('in', 'India'), ('ca', 'Canada'), ('au', 'Australia'), ('fr', 'France'), ('de', 'Germany'), ('qa', 'Qatar'), ('sa', 'Saudi Arabia'), ('ae', 'United Arab Emirates'), ('il', 'Israel'), ('ru', 'Russia'), ('ua', 'Ukraine'), ('hk', 'Hong Kong'), ('jp', 'Japan'), ('sg', 'Singapore'), ('my', 'Malaysia'), ('th', 'Thailand'), ('ph', 'Philippines'), ('cn', 'China'), ('nz', 'New Zealand'), ('bd', 'Bangladesh'), ('tr', 'Turkey'), ('ie', 'Ireland'), ('za', 'South Africa'), ('kr', 'South Korea'), ('tw', 'Taiwan')], default='pk', max_length=5)),
                ('language', models.CharField(default='en', max_length=10)),
                ('bias', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('image_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('politics', 'Politics'), ('business', 'Business'), ('sports', 'Sports'), ('technology', 'Technology'), ('world', 'World'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('finance', 'Finance'), ('science', 'Science')], default='general', max_length=20)),
                ('country', models.CharField(choices=[('pk', 'Pakistan'), ('us', 'United States'), ('gb', 'United Kingdom'), ('in', 'India'), ('ca', 'Canada'), ('au', 'Australia'), ('fr', 'France'), ('de', 'Germany'), ('qa', 'Qatar'), ('sa', 'Saudi Arabia'), ('ae', 'United Arab Emirates'), ('il', 'Israel'), ('ru', 'Russia'), ('ua', 'Ukraine'), ('hk', 'Hong Kong'), ('jp', 'Japan'), ('sg', 'Singapore'), ('my', 'Malaysia'), ('th', 'Thailand'), ('ph', 'Philippines'), ('cn', 'China'), ('nz', 'New Zealand'), ('bd', 'Bangladesh'), ('tr', 'Turkey'), ('ie', 'Ireland'), ('za', 'South Africa'), ('kr', 'South Korea'), ('tw', 'Taiwan')], default='pk', max_length=5)),
                ('language', models.CharField(default='en', max_length=10)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.newscluster')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.source')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
