# Generated by Django 6.0.4 on 2026-07-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='bias',
        ),
        migrations.AddField(
            model_name='news',
            name='bias',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='news',
            name='bias_score',
            field=models.IntegerField(default=50),
        ),
    ]
