# Generated by Django 5.2.16 on 2026-07-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_source_bias_news_bias_news_bias_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='bias',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='source',
            name='bias_score',
            field=models.IntegerField(default=50),
        ),
    ]
