# Generated by Django 5.2.16 on 2026-07-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_source_bias_source_bias_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscluster',
            name='hero_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newscluster',
            name='latest_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
