# Generated by Django 5.2.16 on 2026-07-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newscluster_hero_source_newscluster_latest_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('politics', 'Politics'), ('business', 'Business'), ('finance', 'Finance'), ('technology', 'Technology'), ('sports', 'Sports'), ('health', 'Health'), ('science', 'Science'), ('entertainment', 'Entertainment'), ('world', 'World'), ('crime', 'Crime'), ('education', 'Education'), ('environment', 'Environment'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='newscluster',
            name='category',
            field=models.CharField(choices=[('politics', 'Politics'), ('business', 'Business'), ('finance', 'Finance'), ('technology', 'Technology'), ('sports', 'Sports'), ('health', 'Health'), ('science', 'Science'), ('entertainment', 'Entertainment'), ('world', 'World'), ('crime', 'Crime'), ('education', 'Education'), ('environment', 'Environment'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
