# Generated by Django 5.2.16 on 2026-07-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_category_alter_newscluster_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscluster',
            name='country',
            field=models.CharField(choices=[('pk', 'Pakistan'), ('us', 'United States'), ('gb', 'United Kingdom'), ('in', 'India'), ('ca', 'Canada'), ('au', 'Australia'), ('fr', 'France'), ('de', 'Germany'), ('qa', 'Qatar'), ('sa', 'Saudi Arabia'), ('ae', 'United Arab Emirates'), ('il', 'Israel'), ('ru', 'Russia'), ('ua', 'Ukraine'), ('hk', 'Hong Kong'), ('jp', 'Japan'), ('sg', 'Singapore'), ('my', 'Malaysia'), ('th', 'Thailand'), ('ph', 'Philippines'), ('cn', 'China'), ('nz', 'New Zealand'), ('bd', 'Bangladesh'), ('tr', 'Turkey'), ('ie', 'Ireland'), ('za', 'South Africa'), ('kr', 'South Korea'), ('tw', 'Taiwan')], default='pk', max_length=5),
        ),
        migrations.AddField(
            model_name='newscluster',
            name='is_top_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newscluster',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
