# Generated by Django 5.2.16 on 2026-07-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_savednews'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscluster',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='3-4 paragraph detailed summary'),
        ),
    ]
